apiVersion: apps/v1
kind: Deployment
metadata:
  name: scale-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scale-app
  template:
    metadata:
      labels:
        app: scale-app
    spec:
      containers:
      - name: web
        image: nginx:alpine